[versions]
activity = "1.7.2"
lifecycle = "2.6.1"
navigation = "2.6.0"
room = "2.5.1"

[libraries]
activity-java = { module = "androidx.activity:activity", version.ref = "activity" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
annotation = { module = "androidx.annotation:annotation", version = "1.6.0" }
appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
concurrent-futures = { module = "androidx.concurrent:concurrent-futures", version = "1.1.0" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
core-ktx = { module = "androidx.core:core-ktx", version = "1.10.1" }
lifecycle-livedata-java = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "navigation" }
lifecycle-viewmodel-java = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "navigation" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
navigation-fragment-java = { module = "androidx.navigation:navigation-fragment", version.ref = "navigation" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-java = { module = "androidx.navigation:navigation-ui", version.ref = "navigation" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.3.0" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
startup = { module = "androidx.startup:startup-runtime", version = "1.1.1" }

[bundles]
lifecycle-java = ["lifecycle-livedata-java", "lifecycle-viewmodel-java"]
lifecycle-ktx = ["lifecycle-livedata-ktx", "lifecycle-viewmodel-ktx"]
navigation-java = ["navigation-fragment-java", "navigation-ui-java"]
navigation-ktx = ["navigation-fragment-ktx", "navigation-ui-ktx"]