[versions]
android-gradleplugin = "8.0.1"
kotlin = "1.8.21"

[libraries]
plugin-nexus-publish = { module = "io.github.gradle-nexus:publish-plugin", version = "1.3.0" }
plugin-agp = { module = "com.android.tools.build:gradle", version.ref = "android-gradleplugin" }
plugin-kotlin-android = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
apksig = { module = "com.android.tools.build:apksig", version.ref = "android-gradleplugin" }