[versions]
android-gradleplugin = "8.0.2"
kotlin = "1.8.22"
kotlin-ksp = "1.8.22-1.0.11"

[libraries]
materialcomponents = { module = "com.google.android.material:material", version = "1.9.0" }
plugin-nexus-publish = { module = "io.github.gradle-nexus:publish-plugin", version = "1.3.0" }
plugin-agp = { module = "com.android.tools.build:gradle", version.ref = "android-gradleplugin" }
plugin-kotlin-android = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
apksig = { module = "com.android.tools.build:apksig", version.ref = "android-gradleplugin" }
listenablefuture = { module = "com.google.guava:listenablefuture", version = "1.0" }
guava = { module = "com.google.guava:guava", version = "32.0.1-android" }
viewbindingpropertydelegate = { module = "com.github.kirich1409:viewbindingpropertydelegate-noreflection", version = "1.5.9" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradleplugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }